export const GET_CONTACT_DATA = "GET_CONTACT_DATA";
export const GET_CATEGORY_DATA = "GET_CATEGORY_DATA";
export const SET_CATEGORY = "SET_CATEGORY";
export const GET_CATEGORY_DATAS = "GET_CATEGORY_DATAS";
